[package]
name              = "client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "voxel-game"  # TODO(rename): product name
path = "src/main.rs"

[dependencies]
common.workspace     = true
glam.workspace       = true
log.workspace        = true
env_logger.workspace = true

winit    = "0.30"
wgpu     = "30"
png      = "0.18"
bytemuck = { version = "1", features = ["derive"] }
pollster = "1.0"
anyhow   = "1"

[lints]
workspace = true
